# =========================
# Ubuntu / Toolbox Servers
# =========================
[automation_nodes]

# =========================
# VLAN 20 Ubuntu Nodes
# =========================
[vlan20_nodes]
vlan20-toolbox-2.lab
vlan20-toolbox-5.lab

# =========================
# VLAN 30 Ubuntu Nodes
# =========================
[vlan30_nodes]
vlan30-toolbox-3.lab
vlan30-toolbox-6.lab

# =========================
# VLAN 40 Ubuntu Nodes
# =========================
[vlan40_nodes]
vlan40-toolbox-4.lab
vlan40-toolbox-7.lab

# =========================
# All Linux Nodes
# =========================
[linux_nodes:children]
automation_nodes
vlan20_nodes
vlan30_nodes
vlan40_nodes

# =========================
# Linux Variables
# =========================
[linux_nodes:vars]
ansible_user=root
ansible_connection=ssh
ansible_python_interpreter=/usr/bin/python3

# =========================
# Fortigate Firewalls
# =========================
[fortigate]
gns3lab-fw01.lab
fgt-homelab-fw01.lab

# =========================
# Cisco / Network Devices
# =========================
[cisco_switches]
acc-001.lab
acc-002.lab
d001.lab
d002.lab

# =========================
# Fortigate Variables
# =========================
[fortigate:vars]
ansible_connection=httpapi
ansible_network_os=fortinet.fortios.fortios
ansible_httpapi_use_ssl=true
ansible_httpapi_validate_certs=false
ansible_user=admin
ansible_password=yourpassword
